# .goreleaser.yaml
version: 2
before:
  hooks:
    - go mod tidy

# 🏗 Build configuration
builds:
  - id: paprika-3-mcp
    main: ./cmd/paprika-3-mcp
    binary: paprika-3-mcp
    goos:
      - freebsd
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    ldflags:
      - -s -w -X main.version={{.Version}}

# 📦 Archive configuration
archives:
- formats:
    - zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

# 📝 SHA256 checksums
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

# 📜 Changelog (uses Conventional Commits)
changelog:
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'